import { Country } from './types';

export const ARAB_COUNTRIES: Country[] = [
  { name: "Egypt", nameAr: "مصر", dialCode: "+20", code: "EG", flag: "🇪🇬" },
  { name: "Saudi Arabia", nameAr: "السعودية", dialCode: "+966", code: "SA", flag: "🇸🇦" },
  { name: "UAE", nameAr: "الإمارات", dialCode: "+971", code: "AE", flag: "🇦🇪" },
  { name: "Kuwait", nameAr: "الكويت", dialCode: "+965", code: "KW", flag: "🇰🇼" },
  { name: "Qatar", nameAr: "قطر", dialCode: "+974", code: "QA", flag: "🇶🇦" },
  { name: "Bahrain", nameAr: "البحرين", dialCode: "+973", code: "BH", flag: "🇧🇭" },
  { name: "Oman", nameAr: "عمان", dialCode: "+968", code: "OM", flag: "🇴🇲" },
  { name: "Jordan", nameAr: "الأردن", dialCode: "+962", code: "JO", flag: "🇯🇴" },
  { name: "Lebanon", nameAr: "لبنان", dialCode: "+961", code: "LB", flag: "🇱🇧" },
  { name: "Iraq", nameAr: "العراق", dialCode: "+964", code: "IQ", flag: "🇮🇶" },
  { name: "Yemen", nameAr: "اليمن", dialCode: "+967", code: "YE", flag: "🇾🇪" },
  { name: "Syria", nameAr: "سوريا", dialCode: "+963", code: "SY", flag: "🇸🇾" },
  { name: "Palestine", nameAr: "فلسطين", dialCode: "+970", code: "PS", flag: "🇵🇸" },
  { name: "Sudan", nameAr: "السودان", dialCode: "+249", code: "SD", flag: "🇸🇩" },
  { name: "Libya", nameAr: "ليبيا", dialCode: "+218", code: "LY", flag: "🇱🇾" },
  { name: "Morocco", nameAr: "المغرب", dialCode: "+212", code: "MA", flag: "🇲🇦" },
  { name: "Tunisia", nameAr: "تونس", dialCode: "+216", code: "TN", flag: "🇹🇳" },
  { name: "Algeria", nameAr: "الجزائر", dialCode: "+213", code: "DZ", flag: "🇩🇿" },
  { name: "Mauritania", nameAr: "موريتانيا", dialCode: "+222", code: "MR", flag: "🇲🇷" },
  { name: "Somalia", nameAr: "الصومال", dialCode: "+252", code: "SO", flag: "🇸🇴" },
  { name: "Djibouti", nameAr: "جيبوتي", dialCode: "+253", code: "DJ", flag: "🇩🇯" },
  { name: "Comoros", nameAr: "جزر القمر", dialCode: "+269", code: "KM", flag: "🇰🇲" },
];

export const REST_OF_WORLD: Country[] = [
  { name: "Afghanistan", nameAr: "أفغانستان", dialCode: "+93", code: "AF", flag: "🇦🇫" },
  { name: "Albania", nameAr: "ألبانيا", dialCode: "+355", code: "AL", flag: "🇦🇱" },
  { name: "Argentina", nameAr: "الأرجنتين", dialCode: "+54", code: "AR", flag: "🇦🇷" },
  { name: "Armenia", nameAr: "أرمينيا", dialCode: "+374", code: "AM", flag: "🇦🇲" },
  { name: "Australia", nameAr: "أستراليا", dialCode: "+61", code: "AU", flag: "🇦🇺" },
  { name: "Austria", nameAr: "النمسا", dialCode: "+43", code: "AT", flag: "🇦🇹" },
  { name: "Azerbaijan", nameAr: "أذربيجان", dialCode: "+994", code: "AZ", flag: "🇦🇿" },
  { name: "Bangladesh", nameAr: "بنغلاديش", dialCode: "+880", code: "BD", flag: "🇧🇩" },
  { name: "Belgium", nameAr: "بلجيكا", dialCode: "+32", code: "BE", flag: "🇧🇪" },
  { name: "Bolivia", nameAr: "بوليفيا", dialCode: "+591", code: "BO", flag: "🇧🇴" },
  { name: "Bosnia & Herzegovina", nameAr: "البوسنة والهرسك", dialCode: "+387", code: "BA", flag: "🇧🇦" },
  { name: "Brazil", nameAr: "البرازيل", dialCode: "+55", code: "BR", flag: "🇧🇷" },
  { name: "Bulgaria", nameAr: "بلغاريا", dialCode: "+359", code: "BG", flag: "🇧🇬" },
  { name: "Cambodia", nameAr: "كمبوديا", dialCode: "+855", code: "KH", flag: "🇰🇭" },
  { name: "Canada", nameAr: "كندا", dialCode: "+1", code: "CA", flag: "🇨🇦" },
  { name: "Chile", nameAr: "تشيلي", dialCode: "+56", code: "CL", flag: "🇨🇱" },
  { name: "China", nameAr: "الصين", dialCode: "+86", code: "CN", flag: "🇨🇳" },
  { name: "Colombia", nameAr: "كولومبيا", dialCode: "+57", code: "CO", flag: "🇨🇴" },
  { name: "Costa Rica", nameAr: "كوستاريكا", dialCode: "+506", code: "CR", flag: "🇨🇷" },
  { name: "Croatia", nameAr: "كرواتيا", dialCode: "+385", code: "HR", flag: "🇭🇷" },
  { name: "Cuba", nameAr: "كوبا", dialCode: "+53", code: "CU", flag: "🇨🇺" },
  { name: "Cyprus", nameAr: "قبرص", dialCode: "+357", code: "CY", flag: "🇨🇾" },
  { name: "Czech Republic", nameAr: "التشيك", dialCode: "+420", code: "CZ", flag: "🇨🇿" },
  { name: "Denmark", nameAr: "الدنمارك", dialCode: "+45", code: "DK", flag: "🇩🇰" },
  { name: "Dominican Republic", nameAr: "جمهورية الدومينيكان", dialCode: "+1", code: "DO", flag: "🇩🇴" },
  { name: "Ecuador", nameAr: "الإكوادور", dialCode: "+593", code: "EC", flag: "🇪🇨" },
  { name: "Estonia", nameAr: "إستونيا", dialCode: "+372", code: "EE", flag: "🇪🇪" },
  { name: "Ethiopia", nameAr: "إثيوبيا", dialCode: "+251", code: "ET", flag: "🇪🇹" },
  { name: "Finland", nameAr: "فنلندا", dialCode: "+358", code: "FI", flag: "🇫🇮" },
  { name: "France", nameAr: "فرنسا", dialCode: "+33", code: "FR", flag: "🇫🇷" },
  { name: "Georgia", nameAr: "جورجيا", dialCode: "+995", code: "GE", flag: "🇬🇪" },
  { name: "Germany", nameAr: "ألمانيا", dialCode: "+49", code: "DE", flag: "🇩🇪" },
  { name: "Ghana", nameAr: "غانا", dialCode: "+233", code: "GH", flag: "🇬🇭" },
  { name: "Greece", nameAr: "اليونان", dialCode: "+30", code: "GR", flag: "🇬🇷" },
  { name: "Hong Kong", nameAr: "هونغ كونغ", dialCode: "+852", code: "HK", flag: "🇭🇰" },
  { name: "Hungary", nameAr: "هنغاريا", dialCode: "+36", code: "HU", flag: "🇭🇺" },
  { name: "Iceland", nameAr: "آيسلندا", dialCode: "+354", code: "IS", flag: "🇮🇸" },
  { name: "India", nameAr: "الهند", dialCode: "+91", code: "IN", flag: "🇮🇳" },
  { name: "Indonesia", nameAr: "إندونيسيا", dialCode: "+62", code: "ID", flag: "🇮🇩" },
  { name: "Iran", nameAr: "إيران", dialCode: "+98", code: "IR", flag: "🇮🇷" },
  { name: "Ireland", nameAr: "أيرلندا", dialCode: "+353", code: "IE", flag: "🇮🇪" },
  { name: "Italy", nameAr: "إيطاليا", dialCode: "+39", code: "IT", flag: "🇮🇹" },
  { name: "Japan", nameAr: "اليابان", dialCode: "+81", code: "JP", flag: "🇯🇵" },
  { name: "Kazakhstan", nameAr: "كازاخستان", dialCode: "+7", code: "KZ", flag: "🇰🇿" },
  { name: "Kenya", nameAr: "كينيا", dialCode: "+254", code: "KE", flag: "🇰🇪" },
  { name: "Latvia", nameAr: "لاتفيا", dialCode: "+371", code: "LV", flag: "🇱🇻" },
  { name: "Lithuania", nameAr: "ليتوانيا", dialCode: "+370", code: "LT", flag: "🇱🇹" },
  { name: "Luxembourg", nameAr: "لوكسمبورغ", dialCode: "+352", code: "LU", flag: "🇱🇺" },
  { name: "Malaysia", nameAr: "ماليزيا", dialCode: "+60", code: "MY", flag: "🇲🇾" },
  { name: "Maldives", nameAr: "المالديف", dialCode: "+960", code: "MV", flag: "🇲🇻" },
  { name: "Malta", nameAr: "مالطا", dialCode: "+356", code: "MT", flag: "🇲🇹" },
  { name: "Mexico", nameAr: "المكسيك", dialCode: "+52", code: "MX", flag: "🇲🇽" },
  { name: "Moldova", nameAr: "مولدوفا", dialCode: "+373", code: "MD", flag: "🇲🇩" },
  { name: "Mongolia", nameAr: "منغوليا", dialCode: "+976", code: "MN", flag: "🇲🇳" },
  { name: "Montenegro", nameAr: "الجبل الأسود", dialCode: "+382", code: "ME", flag: "🇲🇪" },
  { name: "Myanmar", nameAr: "ميانمار", dialCode: "+95", code: "MM", flag: "🇲🇲" },
  { name: "Nepal", nameAr: "نيبال", dialCode: "+977", code: "NP", flag: "🇳🇵" },
  { name: "Netherlands", nameAr: "هولندا", dialCode: "+31", code: "NL", flag: "🇳🇱" },
  { name: "New Zealand", nameAr: "نيوزيلندا", dialCode: "+64", code: "NZ", flag: "🇳🇿" },
  { name: "Nigeria", nameAr: "نيجيريا", dialCode: "+234", code: "NG", flag: "🇳🇬" },
  { name: "North Korea", nameAr: "كوريا الشمالية", dialCode: "+850", code: "KP", flag: "🇰🇵" },
  { name: "Norway", nameAr: "النرويج", dialCode: "+47", code: "NO", flag: "🇳🇴" },
  { name: "Pakistan", nameAr: "باكستان", dialCode: "+92", code: "PK", flag: "🇵🇰" },
  { name: "Panama", nameAr: "بنما", dialCode: "+507", code: "PA", flag: "🇵🇦" },
  { name: "Paraguay", nameAr: "باراغواي", dialCode: "+595", code: "PY", flag: "🇵🇾" },
  { name: "Peru", nameAr: "بيرو", dialCode: "+51", code: "PE", flag: "🇵🇪" },
  { name: "Philippines", nameAr: "الفلبين", dialCode: "+63", code: "PH", flag: "🇵🇭" },
  { name: "Poland", nameAr: "بولندا", dialCode: "+48", code: "PL", flag: "🇵🇱" },
  { name: "Portugal", nameAr: "البرتغال", dialCode: "+351", code: "PT", flag: "🇵🇹" },
  { name: "Romania", nameAr: "رومانيا", dialCode: "+40", code: "RO", flag: "🇷🇴" },
  { name: "Russia", nameAr: "روسيا", dialCode: "+7", code: "RU", flag: "🇷🇺" },
  { name: "Senegal", nameAr: "السنغال", dialCode: "+221", code: "SN", flag: "🇸🇳" },
  { name: "Serbia", nameAr: "صربيا", dialCode: "+381", code: "RS", flag: "🇷🇸" },
  { name: "Singapore", nameAr: "سنغافورة", dialCode: "+65", code: "SG", flag: "🇸🇬" },
  { name: "Slovakia", nameAr: "سلوفاكيا", dialCode: "+421", code: "SK", flag: "🇸🇰" },
  { name: "Slovenia", nameAr: "سلوفينيا", dialCode: "+386", code: "SI", flag: "🇸🇮" },
  { name: "South Africa", nameAr: "جنوب أفريقيا", dialCode: "+27", code: "ZA", flag: "🇿🇦" },
  { name: "South Korea", nameAr: "كوريا الجنوبية", dialCode: "+82", code: "KR", flag: "🇰🇷" },
  { name: "Spain", nameAr: "إسبانيا", dialCode: "+34", code: "ES", flag: "🇪🇸" },
  { name: "Sri Lanka", nameAr: "سريلانكا", dialCode: "+94", code: "LK", flag: "🇱🇰" },
  { name: "Sweden", nameAr: "السويد", dialCode: "+46", code: "SE", flag: "🇸🇪" },
  { name: "Switzerland", nameAr: "سويسرا", dialCode: "+41", code: "CH", flag: "🇨🇭" },
  { name: "Taiwan", nameAr: "تايوان", dialCode: "+886", code: "TW", flag: "🇹🇼" },
  { name: "Tajikistan", nameAr: "طاجيكستان", dialCode: "+992", code: "TJ", flag: "🇹🇯" },
  { name: "Tanzania", nameAr: "تنزانيا", dialCode: "+255", code: "TZ", flag: "🇹🇿" },
  { name: "Thailand", nameAr: "تايلاند", dialCode: "+66", code: "TH", flag: "🇹🇭" },
  { name: "Turkey", nameAr: "تركيا", dialCode: "+90", code: "TR", flag: "🇹🇷" },
  { name: "Uganda", nameAr: "أوغندا", dialCode: "+256", code: "UG", flag: "🇺🇬" },
  { name: "Ukraine", nameAr: "أوكرانيا", dialCode: "+380", code: "UA", flag: "🇺🇦" },
  { name: "United Kingdom", nameAr: "المملكة المتحدة", dialCode: "+44", code: "GB", flag: "🇬🇧" },
  { name: "United States", nameAr: "الولايات المتحدة", dialCode: "+1", code: "US", flag: "🇺🇸" },
  { name: "Uruguay", nameAr: "أوروغواي", dialCode: "+598", code: "UY", flag: "🇺🇾" },
  { name: "Uzbekistan", nameAr: "أوزبكستان", dialCode: "+998", code: "UZ", flag: "🇺🇿" },
  { name: "Venezuela", nameAr: "فنزويلا", dialCode: "+58", code: "VE", flag: "🇻🇪" },
  { name: "Vietnam", nameAr: "فيتنام", dialCode: "+84", code: "VN", flag: "🇻🇳" }
];

export const ALL_COUNTRIES = [...ARAB_COUNTRIES, ...REST_OF_WORLD];

export const COUNTRY_VALIDATION: Record<string, { min: number; max: number; startsWith?: string[] }> = {
  EG: { min: 10, max: 10, startsWith: ['1'] },
  SA: { min: 9, max: 9, startsWith: ['5'] },
  AE: { min: 9, max: 9, startsWith: ['5'] },
  KW: { min: 8, max: 8, startsWith: ['4', '5', '6', '9'] },
  QA: { min: 8, max: 8, startsWith: ['3', '5', '6', '7'] },
  BH: { min: 8, max: 8, startsWith: ['3', '6'] },
  OM: { min: 8, max: 8, startsWith: ['7', '9'] },
  JO: { min: 9, max: 9, startsWith: ['7'] },
  LB: { min: 7, max: 8, startsWith: ['3', '7', '8'] },
  IQ: { min: 10, max: 10, startsWith: ['7'] },
  YE: { min: 9, max: 9, startsWith: ['7'] },
  SY: { min: 9, max: 9, startsWith: ['9'] },
  PS: { min: 9, max: 9, startsWith: ['5'] },
  SD: { min: 9, max: 9, startsWith: ['1', '9'] },
  LY: { min: 9, max: 9, startsWith: ['9'] },
  MA: { min: 9, max: 9, startsWith: ['6', '7'] },
  TN: { min: 8, max: 8, startsWith: ['2', '4', '5', '9'] },
  DZ: { min: 9, max: 9, startsWith: ['5', '6', '7'] },
};
